### ISSUE TITLE
Can this library target .NET 4.0?

### ISSUE THREAD

**Issue by NickMRamirez** [swimtver/Topshelf.StructureMap#4]
Topshelf targets .NET framework 4.0, but this project targets .NET 4.5. Is there any reason? It's better to target the lowest framework version possible, for easier deployment to servers that don't have the latest .NET installed. 

Any reason not to downgrade to .NET 4.0?

**Comment by ilopez** [comment]
Looks like you have to install the older 3.3.1 build to get NET 4.0 again.

**Comment by swimtver** [comment]
I close this issue. Think it's not actual now.
