### ISSUE TITLE
Topshelf.Quartz.StructureMap Could not copy the file "app.config" because it was not found.

### ISSUE THREAD

**Issue by oleksabor** [swimtver/Topshelf.StructureMap#5]
Dears

I'd like to build source code into binary but Topshelf.Quartz.StructureMap build fails with error 

> Could not copy the file "app.config" because it was not found.

I've checked Topshelf.Quartz.StructureMap source code and has not found app.config. It builds if I exclude app.config from project but I'm not sure that this is correct way

Regards

**Comment by swimtver** [comment]
It was a correct way. My fault.
