### ISSUE TITLE
Latest version of Topshelf.StructureMap fixed to Topshelf 4.0.0

### ISSUE THREAD

**Issue by danspam** [swimtver/Topshelf.StructureMap#8]
Just tried to update to the latest (0.5.0) version of Topshelf.StructureMap from Nuget and I get:

The type 'HostConfigurator' is defined in an assembly that is not referenced. You must add a reference to assembly 'Topshelf, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.

I am using version 4.0.4 of Topshelf (latest). Is there any way you can make this new release a bit more flexible with the version of Topshelf required?

**Comment by swimtver** [comment]
Thanks, new version is in nuget feed already.
